name: Daily Investment Report

on:
  schedule:
    # Runs at 8 AM EST (1 PM UTC)
    - cron: '0 13 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  send-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate and send report
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        REPORT_EMAIL_TO: ${{ secrets.REPORT_EMAIL_TO }}
        REPORT_EMAIL_FROM: ${{ secrets.REPORT_EMAIL_FROM }}
      run: npm run report
    
    - name: Report status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Daily report sent successfully"
        else
          echo "❌ Failed to send daily report"
        fi